name: 'technical_assessment'
version: '1.0.0'
config-version: 2

profile: 'assessment'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  technical_assessment:
    +schema: technical_assessment
    marts:
      materialized: table
